default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: esc_game_development

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

cache:
  <<: *default
  url: <%= ENV["CACHE_DATABASE_URL"] || ENV["DATABASE_URL"] %>

queue:
  <<: *default
  url: <%= ENV["QUEUE_DATABASE_URL"] || ENV["DATABASE_URL"] %>

cable:
  <<: *default
  url: <%= ENV["CABLE_DATABASE_URL"] || ENV["DATABASE_URL"] %>
